### ISSUE TITLE
Question: Can two AS1115 chips be controlled using this library?

### ISSUE THREAD

**Issue by clone45** [sarahemm/arduino-as1115#1]
Can two AS1115 chips be controlled using this library?  I have two different AS1115 chips on the same I2C line, and I'm worried that the addresses will conflict.  Thanks!

**Comment by sarahemm** [comment]
Yep! You can set two bits of the address, per the datasheet. I'm using this library on a project driving 16 7-segment displays with 2x AS1115s and it's working fine :)
