### ISSUE TITLE
Font, Example Codes and Read Switches

### ISSUE THREAD

**Issue by SamFarah** [sarahemm/arduino-as1115#2]
Awesome library, very well made, but I noticed a few issues:

**Setting the Font**
Setting the font doesn't do much, no matter what you set the font to in the setup it will always take the hex because of the last line in the .begin() function in the CPP file :
`setFont(FONT_HEX);`
Changing  that line to the following would solve the problem:
`setFont(cur_font);` 

**Example Codes**
The example codes that come with it are missing the `display.begin();` function calls, which is not a problem, but might cause someone to spend some time trying to figure out why it doesn't work when they connect everything as it should

**Read Switches**
I noticed that this library does not support reading switches (unless I missed it somehow), I wrote a small function to the library to read them, however the return value I made is suitable for my application, it might not be that useful for others

```
int AS1115::ReadKeys()
{
    byte Data1=as1115ReadRegister(REG_KEYA);
    byte Data2=as1115ReadRegister(REG_KEYB);    
    if (Data1!=0xFF)return log2(byte(~(Data1)))+9;
    else if (Data2!=0xFF)return log2(byte(~(Data2)))+1;
}
```

Then you can create an interrupt in the sketch to handle the read value when IRQ pin goes down

Thanks

**Comment by sarahemm** [comment]
Fixed, thanks very much for the PR!
